### ISSUE TITLE
Prebuilt binary leaks some nix dependency?

### ISSUE THREAD

**Issue by telser** [MangoIV/cabal-audit#32]
Trying to use the prebuilt binary at https://github.com/MangoIV/cabal-audit/releases/download/nightly/cabal-audit, I was hit with `no such file or directory`. 

Running `file` gave me `interpreter /nix/store/k7zgvzp2r31zkg9xqgjim7mbknryv6bs-glibc-2.39-52/lib/ld-linux-x86-64.so.2, for GNU/Linux 3.10.0`, which would seem to indicate that there is some requirement on having nix to even run this?

**Comment by MangoIV** [comment]
indeed! seems like there's an issue with the nix static binary builder! thank you for noticing.

**Comment by MangoIV** [comment]
@telser would you be willing to try out a `pre-release` cabal-audit executable that I have built statically?

**Comment by telser** [comment]
@MangoIV Sure!

**Comment by MangoIV** [comment]
I will attach one here in a minute :)

**Comment by MangoIV** [comment]
[Uploading cabal-audit.zip…]()
you'll have to unzip unfortunately, github doesn't allow uploading raw exes.

**Comment by MangoIV** [comment]
I cannot upload that here :'D

**Comment by MangoIV** [comment]
I just merged develop; as soon as CI has completed, you may download a statix exe from there.

**Comment by MangoIV** [comment]
https://github.com/MangoIV/cabal-audit/releases/tag/nightly

I think you can close this hereafter :)

**Comment by telser** [comment]
@MangoIV That did the trick, thank you!
