### ISSUE TITLE
Detection failure

### ISSUE THREAD

**Issue by blackheaven** [MangoIV/cabal-audit#43]
Hello,

I'm not sure I actually using `cabal-audit` correctly, because I have created a [vulnerable repository](https://github.com/blackheaven/vulnerable-sandbox), and when I run the `nix` command from the README, I have no error display (while I expect `base` and `aeson`).

Is there something more to do?

**Comment by MangoIV** [comment]
no, this should be fine. It also stopped working for me. The issue is I cannot really bisect as the format in security-advisories seems to have changed. I will have a look, thank you for reporting this.

**Comment by MangoIV** [comment]
yeah, this is due to #38, it appears. I will revert it and see whether I can first fix the cvss part and then trouble shoot that.

**Comment by blackheaven** [comment]
Thanks

**Comment by MangoIV** [comment]
fixed by #44
