### ISSUE TITLE
Building without nix

### ISSUE THREAD

**Issue by Benjamin-McRae-Tracsis** [MangoIV/cabal-audit#5]
Hi, I thought it would be good to be able build this project without nix. This is because I tried to build locally but it couldn't find the security advisories repos.

I added the following to the `cabal.project` and things worked fine

```
source-repository-package
  type: git
  subdir: code/hsec-core
  subdir: code/hsec-tools
  subdir: code/cvss
  subdir: code/osv
  location: https://github.com/haskell/security-advisories.git
```

Furthermore, while I couldn't use the pre-made binaries, I could use the binary created from building it myself.

**Comment by MangoIV** [comment]
Good idea. I’m doing something equivalent for the non-nix CI anyway so good to add this to the cabal project anyways! Will do that!
